version: 1
disable_existing_loggers: false

formatters:
    standard:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    error:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: standard
        stream: ext://sys.stdout

    file:
        class: logging.handlers.RotatingFileHandler
        formatter: standard
        filename: "logs/log.log"
        maxBytes: 104857600 # 100MB
        backupCount: 20
        encoding: utf8

loggers:
    app:
        level: DEBUG
        handlers: [console, file]
        propogate: no