---
  #- name: APP | Clone project
  #  git:
  #    repo: https://github.com/humberthomattar/dev-flask.git
  #    dest: "/home/vagrant/flask/{{ app_name }}/app"
  #    clone: yes
  #    update: yes
  #  become: yes
  #  become_user: vagrant
  
  - name: Install requirements
    pip: 
      requirements: "/home/vagrant/{{ app_name }}/requirements.txt"
      virtualenv: "/home/vagrant/flask-env"
    become: yes
    become_user: vagrant
  